Vrode kak bi rabotaet
HollowHorizon/HollowStory pull request #26
Opened 2024-03-30 19:53 UTC by AlgorithmLX

2024-04-02 08:09 UTC, HollowHorizon requested changes

2024-04-02 08:09 UTC, HollowHorizon commented on src/main/java/ru/hollowhorizon/hollowengine/client/ClientEvents.kt
втф, каждый кадр отправлять пакет с текущим скином игрока на сервер, так ещё и на самом сервере пытаться получить локального игрока и его скин? Ты под чем был, когда кодил это?)

2024-04-02 08:09 UTC, HollowHorizon commented on src/main/java/ru/hollowhorizon/hollowengine/common/events/StoryHandler.kt
Почему на сервере ты хранишь скин одного игрока, а если их будет 50?

2024-04-02 08:09 UTC, HollowHorizon commented on src/main/java/ru/hollowhorizon/hollowengine/common/network/HEPackets.kt
На сервере писать `(player as LocalPlayer)` - это конечно гениально, но работать оно не будет...

2024-04-07 11:58 UTC, closed without merging

2024-04-07 16:45 UTC, AlgorithmLX commented on src/main/java/ru/hollowhorizon/hollowengine/client/ClientEvents.kt
лучше тебе не знать))

2024-04-07 16:57 UTC, HollowHorizon commented on src/main/java/ru/hollowhorizon/hollowengine/client/ClientEvents.kt
делись давай, я тоже хочу)

2024-04-07 17:28 UTC, AlgorithmLX commented on src/main/java/ru/hollowhorizon/hollowengine/client/ClientEvents.kt
> делись давай, я тоже хочу)

писал просто после колледжа)